SQSEventRule:
  Type: AWS::Events::Rule
  Properties:
    EventBusName: default
    EventPattern:
      source:
        - aws.sqs
      detail-type:
        - AWS API Call via CloudTrail
      detail:
        eventSource:
          - sqs.amazonaws.com
        eventName:
          - prefix: CreateQueue
          - prefix: SetQueueAttributes
          - prefix: TagQueue
          - prefix: UntagQueue
          - prefix: DeleteQueue
    Name: port-aws-exporter-sync-sqs-trails
    State: ENABLED
    Targets:
      - Id: PortAWSExporterEventsQueue
        Arn:
          Fn::ImportValue:
            Fn::Sub: ${PortAWSExporterStackName}-EventsQueueARN
        InputTransformer:
          InputPathsMap:
            awsRegion: $.detail.awsRegion
            eventName: $.detail.eventName
            requestQueueUrl: $.detail.requestParameters.queueUrl
            responseQueueUrl: $.detail.responseElements.queueUrl
          InputTemplate: |-
            {
              "resource_type": "AWS::SQS::Queue",
              "region": "\"<awsRegion>\"",
              "identifier": "\"<eventName>\" | if test(\"CreateQueue[^a-zA-Z]*$\") then \"<responseQueueUrl>\" elif test(\"DeleteQueue[^a-zA-Z]*$\") then \"<requestQueueUrl>\" | split(\"/\")[-1] else \"<requestQueueUrl>\" end",
              "action": "if \"<eventName>\" | test(\"DeleteQueue[^a-zA-Z]*$\") then \"delete\" else \"upsert\" end"
            }